
export const citiesByProvince = {
  "Aceh": ["Banda Aceh", "Sabang", "Lhokseumawe", "Langsa", "Subulussalam"],
  "Bali": ["Denpasar", "Badung", "Gianyar", "Tabanan", "Buleleng"],
  "Banten": ["Serang", "Cilegon", "Tangerang", "Tangerang Selatan"],
  "Bengkulu": ["Bengkulu", "Curup", "Manna"],
  "Gorontalo": ["Gorontalo", "Limboto"],
  "Jakarta": ["Jakarta Pusat", "Jakarta Barat", "Jakarta Selatan", "Jakarta Timur", "Jakarta Utara"],
  "Jambi": ["Jambi", "Sungai Penuh"],
  "Jawa Barat": ["Bandung", "Bekasi", "Bogor", "Depok", "Cimahi", "Tasikmalaya", "Sukabumi"],
  "Jawa Tengah": ["Semarang", "Surakarta", "Magelang", "Pekalongan", "Salatiga", "Tegal"],
  "Jawa Timur": ["Surabaya", "Malang", "Kediri", "Madiun", "Probolinggo", "Pasuruan", "Batu"],
  "Kalimantan Barat": ["Pontianak", "Singkawang"],
  "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru"],
  "Kalimantan Tengah": ["Palangka Raya"],
  "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang"],
  "Kalimantan Utara": ["Tanjung Selor", "Tarakan"],
  "Kepulauan Bangka Belitung": ["Pangkal Pinang"],
  "Kepulauan Riau": ["Tanjungpinang", "Batam"],
  "Lampung": ["Bandar Lampung", "Metro"],
  "Maluku": ["Ambon", "Tual"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan"],
  "Nusa Tenggara Barat": ["Mataram", "Bima"],
  "Nusa Tenggara Timur": ["Kupang"],
  "Papua": ["Jayapura"],
  "Papua Barat": ["Manokwari"],
  "Papua Barat Daya": ["Sorong"],
  "Papua Pegunungan": ["Wamena"],
  "Papua Selatan": ["Merauke"],
  "Papua Tengah": ["Nabire"],
  "Riau": ["Pekanbaru", "Dumai"],
  "Sulawesi Barat": ["Mamuju"],
  "Sulawesi Selatan": ["Makassar", "Palopo", "Parepare"],
  "Sulawesi Tengah": ["Palu"],
  "Sulawesi Tenggara": ["Kendari", "Baubau"],
  "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Kotamobagu"],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Padang Panjang", "Pariaman", "Payakumbuh", "Sawahlunto", "Solok"],
  "Sumatera Selatan": ["Palembang", "Prabumulih", "Pagar Alam", "Lubuklinggau"],
  "Sumatera Utara": ["Medan", "Pematangsiantar", "Tebing Tinggi", "Tanjungbalai", "Binjai", "Padangsidimpuan", "Gunungsitoli"],
  "Yogyakarta": ["Yogyakarta", "Sleman", "Bantul", "Kulon Progo", "Gunungkidul"],
};
